#common
obstacle_range: 2.5 #default = 2.5
raytrace_range: 3.0 #default = 3.0
footprint: [[0.629, 0.629], [0.629, -0.629], [-0.629, -0.629], [-0.629, 0.629]]
footprint_padding: 0.1

inflation_radius: 0.5

observation_sources: laser

laser:
  {
    topic: scan,
    sensor_frame: scan_link,
    data_type: LaserScan,
    clearing: true,
    marking: true,
    inf_is_valid: true,
    max_obstacle_height: 2.0,
    min_obstacle_height: 0.0,
  }
