TebLocalPlannerROS:
  odom_topic: odom

  # Robot

  max_vel_x: 0.8
  max_vel_x_backwards: 0.8
  max_vel_y: 0.8
  max_vel_theta: 1.2
  acc_lim_x: 1.25
  acc_lim_y: 1.25
  acc_lim_theta: 1.0

  footprint_model:
    type: "polygon"
    vertices: [[-0.285, 0.18], [-0.285, -0.18], [0.285, -0.18], [0.285, 0.18]]

  # GoalTolerance

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: False
  complete_global_plan: True

  # Recovery

  shrink_horizon_backup: True
  shrink_horizon_min_duration: 10
  oscillation_recovery: True
  oscillation_v_eps: 0.1
  oscillation_omega_eps: 0.1
  oscillation_recovery_min_duration: 10
  oscillation_filter_duration: 10
