global_costmap:
  global_frame: map
  robot_base_frame: base_link

  update_frequency: 10
  publish_frequency: 10 # changed from 5 since this works better with mpc-planer
  transform_tolerance: 0.2
  width: 40.0
  height: 40.0
  resolution: 0.05
  # origin_x: -20.0
  # origin_y: -20.0
  rolling_window: false
  static_map: true
  plugins:
    - { name: static_layer, type: "costmap_2d::StaticLayer" }
    - { name: obstacles_layer, type: "costmap_2d::ObstacleLayer" }
    - { name: inflater_layer, type: "costmap_2d::InflationLayer" }
